# Generated by Django 4.2 on 2023-04-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meta_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(default='az', max_length=50)),
                ('agency_cd', models.CharField(max_length=50)),
                ('site_no', models.FloatField()),
                ('station_nm', models.CharField(max_length=100)),
                ('site_tp_cd', models.CharField(max_length=50)),
                ('dec_lat_va', models.FloatField()),
                ('dec_long_va', models.FloatField()),
                ('coord_acy_cd', models.CharField(max_length=10)),
                ('dec_coord_datum_cd', models.CharField(max_length=10)),
                ('alt_va', models.FloatField()),
                ('alt_acy_va', models.FloatField()),
                ('alt_datum_cd', models.CharField(max_length=10)),
                ('huc_cd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='water_reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=50)),
                ('agency_cd', models.CharField(default='USGS', max_length=50)),
                ('site_id', models.FloatField()),
                ('date_time', models.DateTimeField()),
                ('storage_volume', models.FloatField()),
                ('value_estimated', models.CharField(default='A', max_length=50)),
            ],
        ),
    ]
