# Generated by Django 4.2 on 2023-04-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_reservoir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='water_reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=50)),
                ('site_id', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('storage_volume', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ReservoirData',
        ),
    ]
