# Generated by Django 4.2 on 2023-04-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_reservoir', '0002_water_reservoir_delete_reservoirdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_reservoir',
            name='agency_cd',
            field=models.CharField(default='USGS', max_length=50),
        ),
        migrations.AlterField(
            model_name='water_reservoir',
            name='site_id',
            field=models.FloatField(),
        ),
    ]
