# Generated by Django 4.2 on 2023-04-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_reservoir', '0003_water_reservoir_agency_cd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_reservoir',
            name='value_estimated',
            field=models.CharField(default='A', max_length=50),
        ),
    ]
